# docker-compose.yml

version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=your_mongo_uri
      - CLOUDINARY_CLOUD_NAME=xxx
      - CLOUDINARY_API_KEY=xxx
      - CLOUDINARY_API_SECRET=xxx
      - JWT_SECRET=your_secret
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
